export const API_ENDPOINTS = {
  AUTH: {
    login: "/api/auth/login",
    logout: "/api/auth/logout",
    changePassword: "/api/auth/change-password",
    LOGIN: "/api/auth/login",
    LOGOUT: "/api/auth/logout",
    CHANGE_PASSWORD: "/api/auth/change-password",
  },
  OWNER: {
    OVERVIEW: "/api/owner/overview",
    SUPERADMINS: "/api/owner/superadmins",
    CREATE_SUPERADMIN: "/api/owner/superadmins",
    UPDATE_SUPERADMIN: (id: string) => `/api/owner/superadmins/${id}`,
    DELETE_SUPERADMIN: (id: string) => `/api/owner/superadmins/${id}`,
    AUDIT_LOGS: "/api/owner/audit-logs",
    REPORTS: "/api/owner/reports",
  },
  ADMIN: {
    STATS: "/api/admin/stats",
    PRICING: "/api/admin/pricing",
    CONTRACTS: "/api/admin/contracts",
    KASIR_LIST: "/api/admin/kasir",
    CREATE_KASIR: "/api/admin/kasir",
    UPDATE_KASIR: (id: string) => `/api/admin/kasir/${id}`,
    DELETE_KASIR: (id: string) => `/api/admin/kasir/${id}`,
    EXTEND_KASIR: (id: string) => `/api/admin/kasir/${id}/extend`,
    TERMINATE_KASIR: (id: string) => `/api/admin/kasir/${id}/terminate`,
    MONITOR_KASIR: (id: string) => `/api/admin/kasir/${id}/monitor`,
    // Owner endpoints
    OWNERS_LIST: "/api/admin/owners",
    CREATE_OWNER: "/api/admin/owners",
    UPDATE_OWNER: (id: string) => `/api/admin/owners/${id}`,
    DELETE_OWNER: (id: string) => `/api/admin/owners/${id}`,
  },
  USERS: {
    GET_ALL: "/api/users",
    CREATE: "/api/users",
    GET_BY_ID: (id: string) => `/api/users/${id}`,
    UPDATE: (id: string) => `/api/users/${id}`,
    DELETE: (id: string) => `/api/users/${id}`,
  },
  PRODUCT: {
    get10ProductsAvailable: "/api/products",
    get10ProductsNotAvailable: "/api/products",
    addCategory: "/api/categories",
    getCategory: "/api/categories",
    addProduct: "/api/products",
    updateProduct: "/api/products",
    allProduct: "/api/products",
    allProductStatus: "/api/products",
  },
  ORDER: {
    addOrder: "/api/transactions",
  },
  CATEGORIES: {
    GET_ALL: "/api/categories",
    CREATE: "/api/categories",
  },
  PRODUCTS: {
    GET_ALL: "/api/products",
    CREATE: "/api/products",
    UPDATE: (id: string) => `/api/products/${id}`,
    DELETE: (id: string) => `/api/products/${id}`,
  },
  TRANSACTIONS: {
    GET_ALL: "/api/transactions",
    CREATE: "/api/transactions",
    GET_BY_ID: (id: string) => `/api/transactions/${id}`,
    ANALYTICS: "/api/transactions/analytics",
    GET_ANALYTICS: "/api/transactions/analytics",
    BEST_SELLERS: "/api/transactions/best-sellers",
    GET_BEST_SELLERS: "/api/transactions/best-sellers",
  },
};
