import type { Metadata } from "next";
import { Nunito, Nunito_Sans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { ReactQueryProvider } from "@/providers/providers";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const nunitoMono = Nunito({
  variable: "--font-nunito-mono",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${nunitoSans.variable} ${nunitoMono.variable} h-full antialiased`}
    >
      <ReactQueryProvider>
      <body className="min-h-full flex flex-col">{children}</body>
      </ReactQueryProvider>

      <Toaster
      position="top-center"
      richColors
      toastOptions={{style: {
        width: "365px"
      }}}
      />

    </html>
  );
}
